config/routes.rb
Cats::Application.routes.draw do

  devise_for :users

  resources :cats do
  	member do
  		post :like
      delete :unlike
  	end
  end

  resources :users, only: [:index, :show] do
  	member do
      get :cat
      post :follow
      delete :unfollow
    end
    resources :cats, :only => [:index]
    #resources :like, :on => :member #collection
	end 

  match 'favcats', :to => 'users#favcats'
root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :age, :first_name, :last_name, :city, :user_name, :image

  validates_presence_of :email, :password, :age, :first_name, :last_name, :city, :user_name
  validates_uniqueness_of :email, :user_name

  before_validation :ensure_presence_of

  has_many :cats, dependent: :destroy # :dependant => :destroy
  has_many :likes,  :dependent => :destroy
  has_many :liked_cats, :through => :likes, :source => :cat


  has_many :following_users, class_name: 'Follow', foreign_key: 'followed_user_id'
  has_many :followers, through: :following_users, source: :follower

  has_many :followings, class_name: 'Follow', foreign_key: 'user_id'
  has_many :users_followed, through: :followings, source: :followed_user


  def full_name
      "#{first_name} #{last_name}"
  end

  def owns?(cat)
      cat.user == self
  end

  def to_s
    full_name 
  end

  def likes?(cat)
    liked_cats.include? cat
  end

  def like!(cat)
    liked_cats << cat unless likes?(cat)
    #likes?(cat) ? liked_cats(cat).destroy : liked_cats << cat
  end

  def unlike!(cat)
    likes.find_by_cat_id(cat.id).try(:destroy)
  end

  def follows?(user)
    users_followed.include? user
  end

  def follow!(user)
    users_followed << user unless follows?(user)   
  end

  def unfollow!(user)
    users_followed.destroy user
  end  

  protected

    def ensure_presence_of
      self.first_name = 'NoFirstName' if first_name.blank?
      self.last_name = 'NoLastName' if last_name.blank?
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :authenticate_user!

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def favcats
    @cats = current_user.liked_cats
  end

  def all_likes
    @user = User.find(params[:id])
    @user.liked_cats
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow!(@user)
    redirect_to :back, notice: "You're now following #{@user.full_name}"
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow!(@user)
    redirect_to :back, notice: "You've unfollowed #{@user.full_name}"
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

	def follow_button(user)
		if !current_user.follows?(user) and current_user != user
      link_to "Follow", follow_user_path(user), method: :post, class: 'button radius'
    elsif current_user.follows?(user)
      link_to "Unfollow", unfollow_user_path(user), method: :delete, class: 'button radius alert'
    end
  end
	
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.input :image %> 
  </div>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/favcats.html.erb
<h1>Favorite Cats</h1>

<%= render 'cats/grid', :cats => @cats %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Age</th>
    <th>User name</th>
    <th>Email</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.age %></td>
    <td><%= user.user_name %></td>
    <td><%= user.email %></td>
    <td><%= user.city %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= follow_button(user) %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @user.image, width: 200, height: 200 %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Age:</b>
  <%= @user.age %>
</p>
<p>
  <b>User name:</b>
  <%= @user.user_name %>
</p>
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<p>
  <b>City:</b>
  <%= @user.city %>
</p>
<p>
  <% unless @user.cats.blank? %>
  <b>Cats:</b>
    <% i = 0 %>
    <% @user.cats.each do |cat| %>
          <%= i == 3 || cat == @user.cats.last ? cat.name : cat.name + ', ' %>
          <% i += 1 %>
    <% end %>
      <%= link_to 'more...', user_cats_path(@user) %><br>
  <% end %><br>
</p>
<p>
  <%= follow_button(@user) %>
</p>


<%= link_to 'Back', :back %>