config/routes.rb
Cats::Application.routes.draw do

  devise_for :users

  resources :cats do
  	member do
  		post :like
      delete :unlike
  	end
  end

  resources :users, only: [:index, :show] do
  	member do
      get :cat
      post :follow
      delete :unfollow
    end
    resources :cats, :only => [:index]
    #resources :like, :on => :member #collection
	end 

  match 'favcats', :to => 'users#favcats'
root :to => 'pages#index'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
	mount_uploader :image, ImageUploader
  attr_accessible :bio, :name, :breed, :image

  BREEDS = ['Abyssinian', 'Aegean Cat', 'Begal', 'Siamese', 'Ragdoll', 'Persian']

  validates_presence_of :name, :user_id
  before_save :short_bio
  before_update :short_bio
  after_create :notify_followers

  belongs_to :user
  has_many :likes,  :dependent => :destroy
  has_many :likers, :through => :likes, :source => :user

  scope :not_owned_by, lambda { |user|
    user ? where('user_id <> ?', user.id) : scoped
  }

  default_scope { order('cats.created_at desc') }

  BREEDS.each do |breed|
    scope breed.gsub(' ', '_').downcase.to_sym, lambda { where(breed: breed) }
  end

  scope :most_liked, lambda { order('likes') }
  scope :by_breed, lambda { |breed| where('breed = ?', breed)} #the BREED scope does this for you

  def self.not_owned_by(user)
  	#where('user_id <> ?', user.id)
  	user ? where('user_id <> ?', user.id) :scoped
  end
  def short_bio
    self.bio = self.bio[0..50]
  end

  private

  def notify_followers
    self.user.followers.each do |follower|
      CatMailer.notify_follower_new_cat(follower, self).deliver
    end
  end
end 

app/controllers/cats_controller.rb
class CatsController < ApplicationController

	before_filter :authenticate_user!
	before_filter :load_cat, :only => [:destroy, :update, :edit]
	before_filter :load_user, :only => [:index]
	before_filter :authorize_cat!, :only => [:edit, :update, :destroy]

	def new
		@cat = Cat.new
	end

	def create
		@cat = current_user.cats.new(params[:cat])
		if @cat.save
			flash[:notice] = "Created cat successfuly!"
			redirect_to cats_path
		else
			render 'new'
		end
	end

	def index
		if params[:user_id]
    	@user = User.find_by_id(params[:user_id])
  	else
    	@user = current_user
  	end
  	@cats = @user.cats
	end

	def destroy
		#@cat = current_user.cats.find(params[:id])
		if @cat.destroy
			flash[:notice] = "Cat destroyed!"
		else
			flash[:alert] = "Cat is Still alive!"
		end
		redirect_to cats_path #also :back
	end

	def edit
		#@cat = current_user.cat
	end

	def update
		#@cat = current_user.cats.find(params[:id])
		if @cat.update_attributes(params[:cat])
			redirect_to cats_path, :notice => "Cat updated!"
		else
			render 'edit'
		end
	end

	def like
		@cat = Cat.find(params[:id])
		current_user.like!(@cat)
		CatMailer.new_like(@cat, current_user).deliver
		redirect_to :back, notice: "You liked #{current_user.full_name}'s cat: #{@cat.name}"
	end

	 def unlike
    @cat = Cat.find(params[:id])
    current_user.unlike!(@cat)
    CatMailer.new_unlike(@cat, current_user).deliver
    redirect_to :back, notice: "You unliked #{@cat.name}"
  end


	private

		def load_cat
			@cat = Cat.find(params[:id])
		end

		def load_user
			if params[:user_id]
				@user = User.find(params[:user_id])
			else
				@user = current_user
			end
		end

		def authorize_cat!
			deny unless current_user.owns?(@cat)
		end

end

app/helpers/cats_helper.rb
module CatsHelper

	def like_button(cat)
		unless current_user && current_user.likes?(cat)
			link_to "Like", like_cat_path(cat), class: 'button radius small', method: :post 
 		else
			link_to "Unlike", unlike_cat_path(cat), class: 'button radius small alert', method: :delete 
 		end
	end

	def like_button_count(cat)
		if current_user && current_user.likes?(cat) && cat.likes.count > 2
      	"<h6>You and #{cat.likes.count - 1} other people like this cat</h6>".html_safe
    elsif current_user && current_user.likes?(cat) && cat.likes.count > 1
        "<h6>You and one other person likes this cat</h6>".html_safe
    elsif current_user && current_user.likes?(cat)
        "<h6>You like this cat</h6>".html_safe
    elsif cat.likes.count > 0 
    		"<h6>#{cat.likes.count} #{ cat.likes.count > 1 ? 'people like this cat' : 'person likes this cat' }</h6>".html_safe
    end
	end
end

app/views/cats/_form.html.erb
<!-- views/cats/_form.html.erb -->

<%= simple_form_for @cat do |f| %>
	<%= f.input :name, placeholder: 'the name of your cat' %>
	<%= f.input :bio, label: 'A short biography of your cat.' %>
	<!-- <%= f.select :breed, ["Parsi", "Ragdoll", "Siami"]%> -->

	<%= f.input :image %> 

 <%= image_tag cat.image, width: 400, height: 400 unless cat.image.blank? %>
 <p></p>

 <%= f.input :breed, :as => :select, collection: Cat::BREEDS, :include_blank => false %>
	<p></p>

	<%= f.submit button, class: 'button' %>

<% end %>

app/views/cats/_grid.html.erb
<!-- cats/_grid.html.erb -->
<ul class="small-block-grid-2 large-block-grid-3">
  <% @cats.each do |cat| %>
    <li>
      <div class="panel callout feed-item">
        <div class="cat-image">
       		<%= image_tag cat.image.url, width: 200, height: 200 %>
     		</div>
     		<div class="cat-details">
          <h1><%= cat.name %></h1>
          <h3><%= cat.bio %></h3>
          <div class="cat-links">
            <%= like_button_count(cat) %>
            <%= link_to cat.user.full_name, user_path(cat.user_id) unless cat.user == current_user %><p></p><% if can? :update, cat %>
                <%= link_to 'Edit', edit_cat_path(cat) %>
                <%= link_to 'Destroy', cat, method: :delete, 'data-confirm' => 'Are you sure?' %>
              <% end %>
            <%= like_button(cat) %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/cats/edit.html.erb
<!-- views/cats/edit.html.erb -->
<h1>Edit Cat</h1>

<%=	render 'form', :cat => @cat, :button => 'Update' %>

app/views/cats/index.html.erb
<!-- cats/index.html.erb -->
<%= render 'grid', :cats => @cats %>

app/views/cats/new.html.erb
<!-- view/cats/new.html.erb -->
<h1>New Cat</h1>

<%= render 'form', :cat => @cat, :button => 'Create' %>