config/routes.rb
Cats::Application.routes.draw do

  devise_for :users

  resources :cats do
  	member do
  		post :like
      delete :unlike
  	end
  end

  resources :users, only: [:index, :show] do
  	member do
      get :cat
      post :follow
      delete :unfollow
    end
    resources :cats, :only => [:index]
    #resources :like, :on => :member #collection
	end 

  match 'favcats', :to => 'users#favcats'
root :to => 'pages#index'

end

app/views/layouts/_navbar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Home", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to 'Users', users_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'My Cats', cats_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'New Cat', new_cat_path %></li>
      <li class="divider"></li>

      <% if user_signed_in? %>

      <li><%= link_to 'Fave Cats', favcats_path %></li>
      <li class="divider"></li>

            <li><%= link_to 'Show', user_path(current_user.id) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

    </ul>


      <% else %>

        <li><%= link_to 'Login', new_user_session_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Signup', new_user_registration_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "cats" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  	<%= render 'layouts/navbar' %>

    <div class="row">
    	<% if flash[:notice] %>
      <div data-alert class="alert-box success radius">
        <%= notice %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div data-alert class="alert-box alert radius">
        <%= alert %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
      <div class="panel">
        <%= yield %>
      </div>
    </div>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>